name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build F-Droid version
      run: ./gradlew assembleFdroidDebug
    - name: Upload F-Droid APK
      uses: actions/upload-artifact@v4
      with:
        name: quad9-connect-fdroid-test.apk
        path: ./app/build/outputs/apk/fdroid/debug/quad9-aegis-fdroid-debug.apk
    - name: Build Google Play version
      run: ./gradlew assembleGoogleplayDebug
    - name: Upload Google Play APK
      uses: actions/upload-artifact@v4
      with:
        name: quad9-connect-googleplay-test.apk
        path: ./app/build/outputs/apk/googleplay/debug/quad9-aegis-googleplay-debug.apk
